spring.application.name=readBook
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/readnovel
spring.datasource.username=root
spring.datasource.password=
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.access-token-expiration = 600000
jwt.access-token-secret-key = YWNlc3NfMTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6
jwt.refresh-token-expiration = 604800000
jwt.refresh-token-secret-key = cmVmcmVzaF8xMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=
spring.data.redis.host=localhost
spring.data.redis.port=6379
server.address=0.0.0.0